### ISSUE TITLE
Use a non-root user with a high UID to avoid host conflict

### ISSUE THREAD

**Issue by chirangaalwis** [wallarm/ingress#228]
### Description

Suggesting $subject as currently user with ID `101` is in violation of Kubernetes policy - [https://docs.bridgecrew.io/docs/bc_k8s_37](https://docs.bridgecrew.io/docs/bc_k8s_37).

#### Container controller with user ID `10001`

- Can be set via Helm input value - `controller.image.runAsUser`
- Container controller failure - container restarts are experienced

```
F0504 08:52:08.389642       8 ssl.go:390] unexpected error storing fake SSL Cert: could not create PEM certificate file
/etc/ingress-controller/ssl/default-fake-certificate.pem: open /etc/ingress-controller/ssl/default-fake-certificate.pem: permission denied
```

Related issue: https://github.com/kubernetes/ingress-nginx/issues/4061

#### Container `cron` with user ID `10001`

It was noticed that a connection failure doesn't resolve.

```
{"channel":"stdout","iteration":14,"job.command":"timeout 3h /opt/wallarm/ruby/usr/share/wallarm-common/export-metrics -l STDOUT",
"job.position":2,"job.schedule":"* * * * *","level":"info",
"msg":"2023-05-04 09:01:00 ERROR export-metrics[153]: Can't export metrics (Errno::ECONNREFUSED): Failed to open TCP connection to 127.0.0.1:10246 (Connection refused - connect(2)
for \"127.0.0.1\" port 10246)","time":"2023-05-04T09:01:00Z"}
```

#### Container `collectd` with user ID `10001`

Connection failure doesn't resolve

```
[2023-05-04 08:46:28] curl_json plugin: curl_easy_perform failed with status 7: Failed to connect to 127.0.0.1 port 10246: Connection refused (http://127.0.0.1:10246/wallarm-status)
[2023-05-04 08:46:28] read-function of plugin `curl_json-wallarm_nginx-http://127.0.0.1:10246/wallarm-status' failed. Will suspend it for 20.000 seconds.
[2023-05-04 08:46:48] curl_json plugin: curl_easy_perform failed with status 7: Failed to connect to 127.0.0.1 port 10246: Connection refused (http://127.0.0.1:10246/wallarm-status)
[2023-05-04 08:46:48] read-function of plugin `curl_json-wallarm_nginx-http://127.0.0.1:10246/wallarm-status' failed. Will suspend it for 40.000 seconds.
```

**Comment by xDmitriev** [comment]
- As we can see [here](https://github.com/wallarm/ingress/blob/9b26a34d94660f6f852d6e02a62cbafc13e75da3/images/nginx/rootfs/Dockerfile#L55) non-root user is already used in the base image for the controller
- Wallarm helper images are distrolless, there is no possibility to directly exec into them. Helper images also use a non-root user
- The reason for error logs from helper containers is that controller can not start 
- The ability to set user comes from upstream, as you may be noticed there is the same issue
